# Political parties referenced as nominating parties in the Seimas members feed.
# Keyed by transliterated name slug for now; JAR codes + VRK data can enrich later.
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX org:    <http://www.w3.org/ns/org#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <https://schema.org/>

PREFIX dh:   <https://www.w3.org/ns/ldt/document-hierarchy#>
PREFIX sioc: <http://rdfs.org/sioc/ns#>

CONSTRUCT
{
    GRAPH ?graph
    {
        ?graph a dh:Item ;
            sioc:has_container ?container ;
            dct:title ?title ;
            foaf:primaryTopic ?party .

        ?party a org:FormalOrganization, schema:PoliticalParty ;
            skos:prefLabel ?title .
    }
}
WHERE
{
    ?row <#partijos_slug> ?slug ;
        <#iskelusi_partija> ?name .

    BIND(STRLANG(?name, "lt") AS ?title)
    BIND(uri(concat(str($base), "parties/")) AS ?container)
    BIND(uri(concat(str(?container), ?slug, "/")) AS ?graph)
    BIND(uri(concat(str(?graph), "#this")) AS ?party)
}
