# SKOS scheme of Seimas position types, derived from the distinct position
# strings in the members feed (stays in sync with the data automatically),
# plus the fixed "Seimo narys" concept used for tenure memberships.
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX dh:   <https://www.w3.org/ns/ldt/document-hierarchy#>
PREFIX sioc: <http://rdfs.org/sioc/ns#>

CONSTRUCT
{
    GRAPH ?mpGraph
    {
        ?mpGraph a dh:Item ;
            sioc:has_container ?schemeGraph ;
            dct:title "Seimo narys"@lt ;
            foaf:primaryTopic ?mpConcept .
        ?mpConcept a skos:Concept ;
            skos:prefLabel "Seimo narys"@lt, "Member of the Seimas"@en ;
            skos:notation "seimo-narys" ;
            skos:inScheme ?scheme ;
            skos:topConceptOf ?scheme .
    }
    GRAPH ?graph
    {
        ?graph a dh:Item ;
            sioc:has_container ?schemeGraph ;
            dct:title ?label ;
            foaf:primaryTopic ?concept .
        ?concept a skos:Concept ;
            skos:prefLabel ?label ;
            skos:notation ?slug ;
            skos:inScheme ?scheme ;
            skos:topConceptOf ?scheme .
    }
}
WHERE
{
    ?row <#pareigu_slug> ?slug ;
        <#pareigos> ?name .

    BIND(STRLANG(?name, "lt") AS ?label)
    BIND(uri(concat(str($base), "taxonomies/position-types/")) AS ?schemeGraph)
    BIND(uri(concat(str(?schemeGraph), "#this")) AS ?scheme)
    BIND(uri(concat(str(?schemeGraph), "seimo-narys/")) AS ?mpGraph)
    BIND(uri(concat(str(?mpGraph), "#this")) AS ?mpConcept)
    BIND(uri(concat(str(?schemeGraph), ?slug, "/")) AS ?graph)
    BIND(uri(concat(str(?graph), "#this")) AS ?concept)
}
