# JAR legal statuses as a SKOS scheme (bilingual: source provides lt + en labels).
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX dh:   <https://www.w3.org/ns/ldt/document-hierarchy#>
PREFIX sioc: <http://rdfs.org/sioc/ns#>

CONSTRUCT
{
    GRAPH ?graph
    {
        ?graph a dh:Item ;
            sioc:has_container ?schemeGraph ;
            dct:title ?labelLt ;
            foaf:primaryTopic ?concept .
        ?concept a skos:Concept ;
            skos:prefLabel ?labelLt, ?labelEn ;
            skos:notation ?code ;
            skos:inScheme ?scheme ;
            skos:topConceptOf ?scheme .
    }
}
WHERE
{
    ?row <#kodas> ?codeRaw ;
        <#pavadinimas> ?nameLt .
    OPTIONAL { ?row <#name> ?nameEn . FILTER(?nameEn != "") }

    BIND(str(?codeRaw) AS ?code)
    BIND(STRLANG(?nameLt, "lt") AS ?labelLt)
    BIND(IF(BOUND(?nameEn), STRLANG(?nameEn, "en"), ?undef) AS ?labelEn)
    BIND(uri(concat(str($base), "taxonomies/legal-statuses/")) AS ?schemeGraph)
    BIND(uri(concat(str(?schemeGraph), "#this")) AS ?scheme)
    BIND(uri(concat(str(?schemeGraph), encode_for_uri(?code), "/")) AS ?graph)
    BIND(uri(concat(str(?graph), "#this")) AS ?concept)
}
