PREFIX cv:       <http://data.europa.eu/m8g/>
PREFIX dct:      <http://purl.org/dc/terms/>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX schema:   <https://schema.org/>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>
PREFIX atu-type: <http://publications.europa.eu/resource/authority/atu-type/>

PREFIX dh:   <https://www.w3.org/ns/ldt/document-hierarchy#>
PREFIX sioc: <http://rdfs.org/sioc/ns#>

CONSTRUCT
{
    GRAPH ?graph
    {
        ?graph a dh:Item ;
            sioc:has_container ?container ;
            dct:title ?title ;
            foaf:primaryTopic ?unit .

        ?unit a cv:AdminUnit ;
            cv:level atu-type:LTU_APS ;
            skos:prefLabel ?title ;
            skos:notation ?code ;
            dct:identifier ?code ;
            schema:validFrom ?validFrom .
    }
}
WHERE
{
    ?row <#adm_kodas> ?codeRaw ;
        <#pavadinimas> ?name .
    OPTIONAL { ?row <#adm_nuo> ?nuo }

    BIND(str(?codeRaw) AS ?code)
    BIND(STRLANG(concat(?name, " apskritis"), "lt") AS ?title)
    BIND(uri(concat(str($base), "admin-units/")) AS ?container)
    BIND(uri(concat(str(?container), encode_for_uri(?code), "/")) AS ?graph)
    BIND(uri(concat(str(?graph), "#this")) AS ?unit)
    BIND(IF(BOUND(?nuo) && ?nuo != "", STRDT(str(?nuo), xsd:date), ?undef) AS ?validFrom)
}
